version: '3.8'
services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    links:
      - database
    expose:
      - 6002

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5002:5002"

  database:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
