version: '3.8'
services:

  flask:
    build: ./flask
    container_name: mysql_server_ui_flask
    restart: always
    expose:
      - 6002
    networks:
      - apps

  nginx:
    build: ./nginx
    container_name: mysql_server_ui_nginx
    restart: always
    ports:
      - "5002:5002"
    networks:
      - apps

networks:
  apps:
    external:
      name: apps
